#!/bin/bash

# Cores para mensagens
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Função para registrar mensagens de log
log() {
  echo -e "[ ${YELLOW}$(date '+%Y-%m-%d %H:%M:%S')${NC} ] $1"
}

# Função para simular uma barra de carregamento
loading() {
  local pid=$!
  local spin='-\|/'
  local i=0
  while kill -0 $pid 2>/dev/null; do
    local i=$(( (i+1) %4 ))
    printf "\r[${spin:$i:1}] Aguarde... "
    sleep 0.1
  done
  printf "\r[${GREEN}✔${NC}] Concluído!          \n"
}

# Mensagem de início
echo -e "${YELLOW}Iniciando o script.${NC}"

# ...

# Remova ou ajuste a linha do wget conforme necessário

# ...

# Mensagem de conclusão
echo -e "${YELLOW}Script executado com sucesso.${NC}"
